//===============================================================================
// Microsoft patterns & practices
// Developing Applications for SharePoint 2010
//===============================================================================
// Copyright Microsoft Corporation.  All rights reserved.
// This code released under the terms of the 
// Microsoft patterns & practices license (http://msdn.microsoft.com/en-us/library/ee663037.aspx)
//===============================================================================


//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;



public partial class InventoryManagementDataContext : Microsoft.SharePoint.Linq.DataContext {
	
	#region Extensibility Method Definitions
	partial void OnCreated();
	#endregion
	
	public InventoryManagementDataContext(string requestUrl) : 
			base(requestUrl) {
		this.OnCreated();
	}
	
	/// <summary>
	/// Use this list to track upcoming events, status updates or other team news.
	/// </summary>
	[Microsoft.SharePoint.Linq.ListAttribute(Name="Announcements")]
	public Microsoft.SharePoint.Linq.EntityList<Announcement> Announcements {
		get {
			return this.GetList<Announcement>("Announcements");
		}
	}
	
	/// <summary>
	/// Use the Calendar list to keep informed of upcoming meetings, deadlines, and other important events.
	/// </summary>
	[Microsoft.SharePoint.Linq.ListAttribute(Name="Calendar")]
	public Microsoft.SharePoint.Linq.EntityList<CalendarEvent> Calendar {
		get {
			return this.GetList<CalendarEvent>("Calendar");
		}
	}
	
	[Microsoft.SharePoint.Linq.ListAttribute(Name="Categories")]
	public Microsoft.SharePoint.Linq.EntityList<Category> Categories {
		get {
			return this.GetList<Category>("Categories");
		}
	}
	
	/// <summary>
	/// This Document library has the templates to create Web Analytics custom reports for this site collection
	/// </summary>
	[Microsoft.SharePoint.Linq.ListAttribute(Name="Customized Reports")]
	public Microsoft.SharePoint.Linq.EntityList<Document> CustomizedReports {
		get {
			return this.GetList<Document>("Customized Reports");
		}
	}
	
	/// <summary>
	/// This library contains administrator-approved form templates that were activated to this site collection.
	/// </summary>
	[Microsoft.SharePoint.Linq.ListAttribute(Name="Form Templates")]
	public Microsoft.SharePoint.Linq.EntityList<Item> FormTemplates {
		get {
			return this.GetList<Item>("Form Templates");
		}
	}
	
	[Microsoft.SharePoint.Linq.ListAttribute(Name="Inventory Locations")]
	public Microsoft.SharePoint.Linq.EntityList<InventoryLocation> InventoryLocations {
		get {
			return this.GetList<InventoryLocation>("Inventory Locations");
		}
	}
	
	/// <summary>
	/// Use the Links list for links to Web pages that your team members will find interesting or useful.
	/// </summary>
	[Microsoft.SharePoint.Linq.ListAttribute(Name="Links")]
	public Microsoft.SharePoint.Linq.EntityList<Link> Links {
		get {
			return this.GetList<Link>("Links");
		}
	}
	
	[Microsoft.SharePoint.Linq.ListAttribute(Name="Machine Parts")]
	public Microsoft.SharePoint.Linq.EntityList<MachinePart> MachineParts {
		get {
			return this.GetList<MachinePart>("Machine Parts");
		}
	}
	
	[Microsoft.SharePoint.Linq.ListAttribute(Name="Machines")]
	public Microsoft.SharePoint.Linq.EntityList<MachinesMachine> Machines {
		get {
			return this.GetList<MachinesMachine>("Machines");
		}
	}
	
	[Microsoft.SharePoint.Linq.ListAttribute(Name="Manufacturers")]
	public Microsoft.SharePoint.Linq.EntityList<Manufacturer> Manufacturers {
		get {
			return this.GetList<Manufacturer>("Manufacturers");
		}
	}
	
	[Microsoft.SharePoint.Linq.ListAttribute(Name="Part Suppliers")]
	public Microsoft.SharePoint.Linq.EntityList<PartSupplier> PartSuppliers {
		get {
			return this.GetList<PartSupplier>("Part Suppliers");
		}
	}
	
	[Microsoft.SharePoint.Linq.ListAttribute(Name="Parts")]
	public Microsoft.SharePoint.Linq.EntityList<Part> Parts {
		get {
			return this.GetList<Part>("Parts");
		}
	}
	
	/// <summary>
	/// Share a document with the team by adding it to this document library.
	/// </summary>
	[Microsoft.SharePoint.Linq.ListAttribute(Name="Shared Documents")]
	public Microsoft.SharePoint.Linq.EntityList<Document> SharedDocuments {
		get {
			return this.GetList<Document>("Shared Documents");
		}
	}
	
	/// <summary>
	/// Use this library to store files which are included on pages within this site, such as images on Wiki pages.
	/// </summary>
	[Microsoft.SharePoint.Linq.ListAttribute(Name="Site Assets")]
	public Microsoft.SharePoint.Linq.EntityList<Document> SiteAssets {
		get {
			return this.GetList<Document>("Site Assets");
		}
	}
	
	/// <summary>
	/// Use this library to create and store pages on this site.
	/// </summary>
	[Microsoft.SharePoint.Linq.ListAttribute(Name="Site Pages")]
	public Microsoft.SharePoint.Linq.EntityList<WikiPage> SitePages {
		get {
			return this.GetList<WikiPage>("Site Pages");
		}
	}
	
	/// <summary>
	/// Use the style library to store style sheets, such as CSS or XSL files. The style sheets in this gallery can be used by this site or any of its subsites.
	/// </summary>
	[Microsoft.SharePoint.Linq.ListAttribute(Name="Style Library")]
	public Microsoft.SharePoint.Linq.EntityList<Document> StyleLibrary {
		get {
			return this.GetList<Document>("Style Library");
		}
	}
	
	[Microsoft.SharePoint.Linq.ListAttribute(Name="Suppliers")]
	public Microsoft.SharePoint.Linq.EntityList<Supplier> Suppliers {
		get {
			return this.GetList<Supplier>("Suppliers");
		}
	}
	
	/// <summary>
	/// Use the Tasks list to keep track of work that you or your team needs to complete.
	/// </summary>
	[Microsoft.SharePoint.Linq.ListAttribute(Name="Tasks")]
	public Microsoft.SharePoint.Linq.EntityList<Item> Tasks {
		get {
			return this.GetList<Item>("Tasks");
		}
	}
	
	/// <summary>
	/// Use the Team Discussion list to hold newsgroup-style discussions on topics relevant to your team.
	/// </summary>
	[Microsoft.SharePoint.Linq.ListAttribute(Name="Team Discussion")]
	public Microsoft.SharePoint.Linq.EntityList<Item> TeamDiscussion {
		get {
			return this.GetList<Item>("Team Discussion");
		}
	}
}

/// <summary>
/// Create a new list item.
/// </summary>
[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Item", Id="0x01")]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(Announcement))]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(Folder))]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(Event))]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(Category))]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(Document))]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(InventoryLocation))]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(Link))]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(MachinePart))]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(Machine))]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(Manufacturer))]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(PartSupplier))]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(Part))]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(Supplier))]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(Task))]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(Message))]
public partial class Item : Microsoft.SharePoint.Linq.ITrackEntityState, Microsoft.SharePoint.Linq.ITrackOriginalValues, System.ComponentModel.INotifyPropertyChanged, System.ComponentModel.INotifyPropertyChanging {
	
	private System.Nullable<int> _id;
	
	private System.Nullable<int> _version;
	
	private string _path;
	
	private Microsoft.SharePoint.Linq.EntityState _entityState;
	
	private System.Collections.Generic.IDictionary<string, object> _originalValues;
	
	protected string _title;
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion

	Microsoft.SharePoint.Linq.EntityState Microsoft.SharePoint.Linq.ITrackEntityState.EntityState {
		get {
			return this._entityState;
		}
		set {
			if ((value != this._entityState)) {
				this._entityState = value;
			}
		}
	}

	System.Collections.Generic.IDictionary<string, object> Microsoft.SharePoint.Linq.ITrackOriginalValues.OriginalValues {
		get {
			if ((null == this._originalValues)) {
				this._originalValues = new System.Collections.Generic.Dictionary<string, object>();
			}
			return this._originalValues;
		}
	}
	
	public Item() {
		this.OnCreated();
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="ID", Storage="_id", ReadOnly=true, FieldType="Counter")]
	public System.Nullable<int> Id {
		get {
			return this._id;
		}
		set {
			if ((value != this._id)) {
				this.OnPropertyChanging("Id", this._id);
				this._id = value;
				this.OnPropertyChanged("Id");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="owshiddenversion", Storage="_version", ReadOnly=true, FieldType="Integer")]
	public System.Nullable<int> Version {
		get {
			return this._version;
		}
		set {
			if ((value != this._version)) {
				this.OnPropertyChanging("Version", this._version);
				this._version = value;
				this.OnPropertyChanged("Version");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="FileDirRef", Storage="_path", ReadOnly=true, FieldType="Lookup", IsLookupValue=true)]
	public string Path {
		get {
			return this._path;
		}
		set {
			if ((value != this._path)) {
				this.OnPropertyChanging("Path", this._path);
				this._path = value;
				this.OnPropertyChanged("Path");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Title", Storage="_title", Required=true, FieldType="Text")]
	public virtual string Title {
		get {
			return this._title;
		}
		set {
			if ((value != this._title)) {
				this.OnPropertyChanging("Title", this._title);
				this._title = value;
				this.OnPropertyChanged("Title");
			}
		}
	}
	
	public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
	
	public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
	
	protected virtual void OnPropertyChanged(string propertyName) {
		if ((null != this.PropertyChanged)) {
			this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
		}
	}
	
	protected virtual void OnPropertyChanging(string propertyName, object value) {
		if ((null == this._originalValues)) {
			this._originalValues = new System.Collections.Generic.Dictionary<string, object>();
		}
		if ((false == this._originalValues.ContainsKey(propertyName))) {
			this._originalValues.Add(propertyName, value);
		}
		if ((null != this.PropertyChanging)) {
			this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
		}
	}
}

/// <summary>
/// Create a new news item, status or other short piece of information.
/// </summary>
[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Announcement", Id="0x0104")]
public partial class Announcement : Item {
	
	private string _body;
	
	private System.Nullable<System.DateTime> _expires;
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public Announcement() {
		this.OnCreated();
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Body", Storage="_body", FieldType="Note")]
	public string Body {
		get {
			return this._body;
		}
		set {
			if ((value != this._body)) {
				this.OnPropertyChanging("Body", this._body);
				this._body = value;
				this.OnPropertyChanged("Body");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Expires", Storage="_expires", FieldType="DateTime")]
	public System.Nullable<System.DateTime> Expires {
		get {
			return this._expires;
		}
		set {
			if ((value != this._expires)) {
				this.OnPropertyChanging("Expires", this._expires);
				this._expires = value;
				this.OnPropertyChanged("Expires");
			}
		}
	}
}

/// <summary>
/// Create a new folder.
/// </summary>
[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Folder", Id="0x0120")]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(SummaryTask))]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(Discussion))]
public partial class Folder : Item {
	
	private string _name;
	
	private System.Nullable<int> _itemChildCountId;
	
	private string _itemChildCountItemChildCount;
	
	private System.Nullable<int> _folderChildCountId;
	
	private string _folderChildCountFolderChildCount;
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public Folder() {
		this.OnCreated();
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="FileLeafRef", Storage="_name", Required=true, FieldType="File")]
	public virtual string Name {
		get {
			return this._name;
		}
		set {
			if ((value != this._name)) {
				this.OnPropertyChanging("Name", this._name);
				this._name = value;
				this.OnPropertyChanged("Name");
			}
		}
	}
	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	[Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
	public override string Title {
		get {
			throw new System.InvalidOperationException("Field Title was removed from content type Folder.");
		}
		set {
			throw new System.InvalidOperationException("Field Title was removed from content type Folder.");
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="ItemChildCount", Storage="_itemChildCountId", ReadOnly=true, FieldType="Lookup", IsLookupId=true)]
	public System.Nullable<int> ItemChildCountId {
		get {
			return this._itemChildCountId;
		}
		set {
			if ((value != this._itemChildCountId)) {
				this.OnPropertyChanging("ItemChildCountId", this._itemChildCountId);
				this._itemChildCountId = value;
				this.OnPropertyChanged("ItemChildCountId");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="ItemChildCount", Storage="_itemChildCountItemChildCount", ReadOnly=true, FieldType="Lookup", IsLookupValue=true)]
	public string ItemChildCountItemChildCount {
		get {
			return this._itemChildCountItemChildCount;
		}
		set {
			if ((value != this._itemChildCountItemChildCount)) {
				this.OnPropertyChanging("ItemChildCountItemChildCount", this._itemChildCountItemChildCount);
				this._itemChildCountItemChildCount = value;
				this.OnPropertyChanged("ItemChildCountItemChildCount");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="FolderChildCount", Storage="_folderChildCountId", ReadOnly=true, FieldType="Lookup", IsLookupId=true)]
	public System.Nullable<int> FolderChildCountId {
		get {
			return this._folderChildCountId;
		}
		set {
			if ((value != this._folderChildCountId)) {
				this.OnPropertyChanging("FolderChildCountId", this._folderChildCountId);
				this._folderChildCountId = value;
				this.OnPropertyChanged("FolderChildCountId");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="FolderChildCount", Storage="_folderChildCountFolderChildCount", ReadOnly=true, FieldType="Lookup", IsLookupValue=true)]
	public string FolderChildCountFolderChildCount {
		get {
			return this._folderChildCountFolderChildCount;
		}
		set {
			if ((value != this._folderChildCountFolderChildCount)) {
				this.OnPropertyChanging("FolderChildCountFolderChildCount", this._folderChildCountFolderChildCount);
				this._folderChildCountFolderChildCount = value;
				this.OnPropertyChanged("FolderChildCountFolderChildCount");
			}
		}
	}
}

/// <summary>
/// Create a new meeting, deadline or other event.
/// </summary>
[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Event", Id="0x0102")]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(CalendarEvent))]
public partial class Event : Item {
	
	private string _location;
	
	protected System.Nullable<System.DateTime> _startTime;
	
	private System.Nullable<System.DateTime> _endTime;
	
	protected string _description;
	
	private System.Nullable<bool> _allDayEvent;
	
	private System.Nullable<bool> _recurrence;
	
	private System.Nullable<bool> _workspace;
	
	private System.Nullable<Category0> _category;
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public Event() {
		this.OnCreated();
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Location", Storage="_location", FieldType="Text")]
	public string Location {
		get {
			return this._location;
		}
		set {
			if ((value != this._location)) {
				this.OnPropertyChanging("Location", this._location);
				this._location = value;
				this.OnPropertyChanged("Location");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="StartDate", Storage="_startTime", Required=true, FieldType="DateTime")]
	public virtual System.Nullable<System.DateTime> StartTime {
		get {
			return this._startTime;
		}
		set {
			if ((value != this._startTime)) {
				this.OnPropertyChanging("StartTime", this._startTime);
				this._startTime = value;
				this.OnPropertyChanged("StartTime");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="EndDate", Storage="_endTime", Required=true, FieldType="DateTime")]
	public System.Nullable<System.DateTime> EndTime {
		get {
			return this._endTime;
		}
		set {
			if ((value != this._endTime)) {
				this.OnPropertyChanging("EndTime", this._endTime);
				this._endTime = value;
				this.OnPropertyChanged("EndTime");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Comments", Storage="_description", FieldType="Note")]
	public virtual string Description {
		get {
			return this._description;
		}
		set {
			if ((value != this._description)) {
				this.OnPropertyChanging("Description", this._description);
				this._description = value;
				this.OnPropertyChanged("Description");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="fAllDayEvent", Storage="_allDayEvent", FieldType="AllDayEvent")]
	public System.Nullable<bool> AllDayEvent {
		get {
			return this._allDayEvent;
		}
		set {
			if ((value != this._allDayEvent)) {
				this.OnPropertyChanging("AllDayEvent", this._allDayEvent);
				this._allDayEvent = value;
				this.OnPropertyChanged("AllDayEvent");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="fRecurrence", Storage="_recurrence", FieldType="Recurrence")]
	public System.Nullable<bool> Recurrence {
		get {
			return this._recurrence;
		}
		set {
			if ((value != this._recurrence)) {
				this.OnPropertyChanging("Recurrence", this._recurrence);
				this._recurrence = value;
				this.OnPropertyChanged("Recurrence");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="WorkspaceLink", Storage="_workspace", FieldType="CrossProjectLink")]
	public System.Nullable<bool> Workspace {
		get {
			return this._workspace;
		}
		set {
			if ((value != this._workspace)) {
				this.OnPropertyChanging("Workspace", this._workspace);
				this._workspace = value;
				this.OnPropertyChanged("Workspace");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Category", Storage="_category", FieldType="Choice")]
	public System.Nullable<Category0> Category {
		get {
			return this._category;
		}
		set {
			if ((value != this._category)) {
				this.OnPropertyChanging("Category", this._category);
				this._category = value;
				this.OnPropertyChanged("Category");
			}
		}
	}
}

/// <summary>
/// Create a new document.
/// </summary>
[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Document", Id="0x0101")]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(WikiPage))]
public partial class Document : Item {
	
	private string _name;
	
	private string _documentModifiedBy;
	
	private string _documentCreatedBy;
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public Document() {
		this.OnCreated();
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="FileLeafRef", Storage="_name", Required=true, FieldType="File")]
	public string Name {
		get {
			return this._name;
		}
		set {
			if ((value != this._name)) {
				this.OnPropertyChanging("Name", this._name);
				this._name = value;
				this.OnPropertyChanged("Name");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Modified_x0020_By", Storage="_documentModifiedBy", ReadOnly=true, FieldType="Text")]
	public string DocumentModifiedBy {
		get {
			return this._documentModifiedBy;
		}
		set {
			if ((value != this._documentModifiedBy)) {
				this.OnPropertyChanging("DocumentModifiedBy", this._documentModifiedBy);
				this._documentModifiedBy = value;
				this.OnPropertyChanged("DocumentModifiedBy");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Created_x0020_By", Storage="_documentCreatedBy", ReadOnly=true, FieldType="Text")]
	public string DocumentCreatedBy {
		get {
			return this._documentCreatedBy;
		}
		set {
			if ((value != this._documentCreatedBy)) {
				this.OnPropertyChanging("DocumentCreatedBy", this._documentCreatedBy);
				this._documentCreatedBy = value;
				this.OnPropertyChanged("DocumentCreatedBy");
			}
		}
	}
}

/// <summary>
/// Create a new link to a Web page or other resource.
/// </summary>
[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Link", Id="0x0105")]
public partial class Link : Item {
	
	private string _uRL;
	
	private string _comments;
	
	private string _uRL0;
	
	private string _uRL1;
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public Link() {
		this.OnCreated();
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="URL", Storage="_uRL", Required=true, FieldType="Url")]
	public string URL {
		get {
			return this._uRL;
		}
		set {
			if ((value != this._uRL)) {
				this.OnPropertyChanging("URL", this._uRL);
				this._uRL = value;
				this.OnPropertyChanged("URL");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Comments", Storage="_comments", FieldType="Note")]
	public string Comments {
		get {
			return this._comments;
		}
		set {
			if ((value != this._comments)) {
				this.OnPropertyChanging("Comments", this._comments);
				this._comments = value;
				this.OnPropertyChanged("Comments");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="URLwMenu", Storage="_uRL0", ReadOnly=true, FieldType="Computed")]
	public string URL0 {
		get {
			return this._uRL0;
		}
		set {
			if ((value != this._uRL0)) {
				this.OnPropertyChanging("URL0", this._uRL0);
				this._uRL0 = value;
				this.OnPropertyChanged("URL0");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="URLNoMenu", Storage="_uRL1", ReadOnly=true, FieldType="Computed")]
	public string URL1 {
		get {
			return this._uRL1;
		}
		set {
			if ((value != this._uRL1)) {
				this.OnPropertyChanging("URL1", this._uRL1);
				this._uRL1 = value;
				this.OnPropertyChanged("URL1");
			}
		}
	}
	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	[Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
	public override string Title {
		get {
			throw new System.InvalidOperationException("Field Title was removed from content type Link.");
		}
		set {
			throw new System.InvalidOperationException("Field Title was removed from content type Link.");
		}
	}
}

/// <summary>
/// Track a work item that you or your team needs to complete.
/// </summary>
[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Task", Id="0x0108")]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(TasksTask))]
public partial class Task : Item {
	
	private System.Nullable<double> _complete;
	
	private string _body;
	
	private System.Nullable<System.DateTime> _startDate;
	
	protected System.Nullable<System.DateTime> _dueDate;
	
	private System.Nullable<Priority> _priority;
	
	protected System.Nullable<TaskStatus> _taskStatus;
	
	private System.Nullable<int> _assignedToId;
	
	private string _assignedTo;
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public Task() {
		this.OnCreated();
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="PercentComplete", Storage="_complete", FieldType="Number")]
	public System.Nullable<double> Complete {
		get {
			return this._complete;
		}
		set {
			if ((value != this._complete)) {
				this.OnPropertyChanging("Complete", this._complete);
				this._complete = value;
				this.OnPropertyChanged("Complete");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Body", Storage="_body", FieldType="Note")]
	public string Body {
		get {
			return this._body;
		}
		set {
			if ((value != this._body)) {
				this.OnPropertyChanging("Body", this._body);
				this._body = value;
				this.OnPropertyChanged("Body");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="StartDate", Storage="_startDate", FieldType="DateTime")]
	public System.Nullable<System.DateTime> StartDate {
		get {
			return this._startDate;
		}
		set {
			if ((value != this._startDate)) {
				this.OnPropertyChanging("StartDate", this._startDate);
				this._startDate = value;
				this.OnPropertyChanged("StartDate");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="TaskDueDate", Storage="_dueDate", FieldType="DateTime")]
	public virtual System.Nullable<System.DateTime> DueDate {
		get {
			return this._dueDate;
		}
		set {
			if ((value != this._dueDate)) {
				this.OnPropertyChanging("DueDate", this._dueDate);
				this._dueDate = value;
				this.OnPropertyChanged("DueDate");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Priority", Storage="_priority", FieldType="Choice")]
	public System.Nullable<Priority> Priority {
		get {
			return this._priority;
		}
		set {
			if ((value != this._priority)) {
				this.OnPropertyChanging("Priority", this._priority);
				this._priority = value;
				this.OnPropertyChanged("Priority");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="TaskStatus", Storage="_taskStatus", FieldType="Choice")]
	public virtual System.Nullable<TaskStatus> TaskStatus {
		get {
			return this._taskStatus;
		}
		set {
			if ((value != this._taskStatus)) {
				this.OnPropertyChanging("TaskStatus", this._taskStatus);
				this._taskStatus = value;
				this.OnPropertyChanged("TaskStatus");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="AssignedTo", Storage="_assignedToId", FieldType="User", IsLookupId=true)]
	public System.Nullable<int> AssignedToId {
		get {
			return this._assignedToId;
		}
		set {
			if ((value != this._assignedToId)) {
				this.OnPropertyChanging("AssignedToId", this._assignedToId);
				this._assignedToId = value;
				this.OnPropertyChanged("AssignedToId");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="AssignedTo", Storage="_assignedTo", ReadOnly=true, FieldType="User", IsLookupValue=true)]
	public string AssignedTo {
		get {
			return this._assignedTo;
		}
		set {
			if ((value != this._assignedTo)) {
				this.OnPropertyChanging("AssignedTo", this._assignedTo);
				this._assignedTo = value;
				this.OnPropertyChanged("AssignedTo");
			}
		}
	}
}

/// <summary>
/// Create a new message.
/// </summary>
[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Message", Id="0x0107")]
public partial class Message : Item {
	
	private string _discussionSubject;
	
	private string _version0;
	
	private string _body;
	
	private string _reply;
	
	private string _post;
	
	private string _threading;
	
	private string _postedBy;
	
	private string _eMailSender;
	
	private System.Nullable<int> _modifiedById;
	
	private string _modifiedByNameWithPicture;
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public Message() {
		this.OnCreated();
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="DiscussionTitle", Storage="_discussionSubject", ReadOnly=true, FieldType="Computed")]
	public string DiscussionSubject {
		get {
			return this._discussionSubject;
		}
		set {
			if ((value != this._discussionSubject)) {
				this.OnPropertyChanging("DiscussionSubject", this._discussionSubject);
				this._discussionSubject = value;
				this.OnPropertyChanged("DiscussionSubject");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="_UIVersionString", Storage="_version0", ReadOnly=true, FieldType="Text")]
	public string Version0 {
		get {
			return this._version0;
		}
		set {
			if ((value != this._version0)) {
				this.OnPropertyChanging("Version0", this._version0);
				this._version0 = value;
				this.OnPropertyChanged("Version0");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Body", Storage="_body", FieldType="Note")]
	public string Body {
		get {
			return this._body;
		}
		set {
			if ((value != this._body)) {
				this.OnPropertyChanging("Body", this._body);
				this._body = value;
				this.OnPropertyChanged("Body");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="ReplyNoGif", Storage="_reply", ReadOnly=true, FieldType="Computed")]
	public string Reply {
		get {
			return this._reply;
		}
		set {
			if ((value != this._reply)) {
				this.OnPropertyChanging("Reply", this._reply);
				this._reply = value;
				this.OnPropertyChanged("Reply");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="BodyAndMore", Storage="_post", ReadOnly=true, FieldType="Computed")]
	public string Post {
		get {
			return this._post;
		}
		set {
			if ((value != this._post)) {
				this.OnPropertyChanging("Post", this._post);
				this._post = value;
				this.OnPropertyChanged("Post");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Threading", Storage="_threading", ReadOnly=true, FieldType="Computed")]
	public string Threading {
		get {
			return this._threading;
		}
		set {
			if ((value != this._threading)) {
				this.OnPropertyChanging("Threading", this._threading);
				this._threading = value;
				this.OnPropertyChanged("Threading");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="PersonViewMinimal", Storage="_postedBy", ReadOnly=true, FieldType="Computed")]
	public string PostedBy {
		get {
			return this._postedBy;
		}
		set {
			if ((value != this._postedBy)) {
				this.OnPropertyChanging("PostedBy", this._postedBy);
				this._postedBy = value;
				this.OnPropertyChanged("PostedBy");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="EmailSender", Storage="_eMailSender", FieldType="Note")]
	public string EMailSender {
		get {
			return this._eMailSender;
		}
		set {
			if ((value != this._eMailSender)) {
				this.OnPropertyChanging("EMailSender", this._eMailSender);
				this._eMailSender = value;
				this.OnPropertyChanged("EMailSender");
			}
		}
	}
	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	[Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
	public override string Title {
		get {
			throw new System.InvalidOperationException("Field Title was removed from content type Message.");
		}
		set {
			throw new System.InvalidOperationException("Field Title was removed from content type Message.");
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="MyEditor", Storage="_modifiedById", ReadOnly=true, FieldType="User", IsLookupId=true)]
	public System.Nullable<int> ModifiedById {
		get {
			return this._modifiedById;
		}
		set {
			if ((value != this._modifiedById)) {
				this.OnPropertyChanging("ModifiedById", this._modifiedById);
				this._modifiedById = value;
				this.OnPropertyChanged("ModifiedById");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="MyEditor", Storage="_modifiedByNameWithPicture", ReadOnly=true, FieldType="User", IsLookupValue=true)]
	public string ModifiedByNameWithPicture {
		get {
			return this._modifiedByNameWithPicture;
		}
		set {
			if ((value != this._modifiedByNameWithPicture)) {
				this.OnPropertyChanging("ModifiedByNameWithPicture", this._modifiedByNameWithPicture);
				this._modifiedByNameWithPicture = value;
				this.OnPropertyChanged("ModifiedByNameWithPicture");
			}
		}
	}
}

/// <summary>
/// Create a new wiki page.
/// </summary>
[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Wiki Page", Id="0x010108")]
public partial class WikiPage : Document {
	
	private string _wikiContent;
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public WikiPage() {
		this.OnCreated();
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="WikiField", Storage="_wikiContent", FieldType="Note")]
	public string WikiContent {
		get {
			return this._wikiContent;
		}
		set {
			if ((value != this._wikiContent)) {
				this.OnPropertyChanging("WikiContent", this._wikiContent);
				this._wikiContent = value;
				this.OnPropertyChanged("WikiContent");
			}
		}
	}
	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	[Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
	public override string Title {
		get {
			throw new System.InvalidOperationException("Field Title was removed from content type Wiki Page.");
		}
		set {
			throw new System.InvalidOperationException("Field Title was removed from content type Wiki Page.");
		}
	}
}

/// <summary>
/// Group and describe related tasks that you or your team needs to complete.
/// </summary>
[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Summary Task", Id="0x012004")]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(TasksSummaryTask))]
public partial class SummaryTask : Folder {
	
	private System.Nullable<double> _complete;
	
	private string _body;
	
	private System.Nullable<System.DateTime> _startDate;
	
	protected System.Nullable<System.DateTime> _dueDate;
	
	private System.Nullable<Priority> _priority;
	
	protected System.Nullable<TaskStatus> _taskStatus;
	
	private System.Nullable<int> _assignedToId;
	
	private string _assignedTo;
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public SummaryTask() {
		this.OnCreated();
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="PercentComplete", Storage="_complete", FieldType="Number")]
	public System.Nullable<double> Complete {
		get {
			return this._complete;
		}
		set {
			if ((value != this._complete)) {
				this.OnPropertyChanging("Complete", this._complete);
				this._complete = value;
				this.OnPropertyChanged("Complete");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Body", Storage="_body", FieldType="Note")]
	public string Body {
		get {
			return this._body;
		}
		set {
			if ((value != this._body)) {
				this.OnPropertyChanging("Body", this._body);
				this._body = value;
				this.OnPropertyChanged("Body");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="StartDate", Storage="_startDate", FieldType="DateTime")]
	public System.Nullable<System.DateTime> StartDate {
		get {
			return this._startDate;
		}
		set {
			if ((value != this._startDate)) {
				this.OnPropertyChanging("StartDate", this._startDate);
				this._startDate = value;
				this.OnPropertyChanged("StartDate");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="TaskDueDate", Storage="_dueDate", FieldType="DateTime")]
	public virtual System.Nullable<System.DateTime> DueDate {
		get {
			return this._dueDate;
		}
		set {
			if ((value != this._dueDate)) {
				this.OnPropertyChanging("DueDate", this._dueDate);
				this._dueDate = value;
				this.OnPropertyChanged("DueDate");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Priority", Storage="_priority", FieldType="Choice")]
	public System.Nullable<Priority> Priority {
		get {
			return this._priority;
		}
		set {
			if ((value != this._priority)) {
				this.OnPropertyChanging("Priority", this._priority);
				this._priority = value;
				this.OnPropertyChanged("Priority");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="TaskStatus", Storage="_taskStatus", FieldType="Choice")]
	public virtual System.Nullable<TaskStatus> TaskStatus {
		get {
			return this._taskStatus;
		}
		set {
			if ((value != this._taskStatus)) {
				this.OnPropertyChanging("TaskStatus", this._taskStatus);
				this._taskStatus = value;
				this.OnPropertyChanged("TaskStatus");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="AssignedTo", Storage="_assignedToId", FieldType="User", IsLookupId=true)]
	public System.Nullable<int> AssignedToId {
		get {
			return this._assignedToId;
		}
		set {
			if ((value != this._assignedToId)) {
				this.OnPropertyChanging("AssignedToId", this._assignedToId);
				this._assignedToId = value;
				this.OnPropertyChanged("AssignedToId");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="AssignedTo", Storage="_assignedTo", ReadOnly=true, FieldType="User", IsLookupValue=true)]
	public string AssignedTo {
		get {
			return this._assignedTo;
		}
		set {
			if ((value != this._assignedTo)) {
				this.OnPropertyChanging("AssignedTo", this._assignedTo);
				this._assignedTo = value;
				this.OnPropertyChanged("AssignedTo");
			}
		}
	}
}

/// <summary>
/// Create a new discussion topic.
/// </summary>
[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Discussion", Id="0x012002")]
public partial class Discussion : Folder {
	
	private string _discussionSubject;
	
	private string _version0;
	
	private string _body;
	
	private string _reply;
	
	private string _post;
	
	private string _threading;
	
	private string _postedBy;
	
	private System.Nullable<System.DateTime> _lastUpdated;
	
	private string _eMailSender;
	
	private System.Nullable<int> _modifiedById;
	
	private string _modifiedByNameWithPicture;
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public Discussion() {
		this.OnCreated();
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Title", Storage="_title", Required=true, FieldType="Text")]
	public override string Title {
		get {
			return this._title;
		}
		set {
			if ((value != this._title)) {
				this.OnPropertyChanging("Title", this._title);
				this._title = value;
				this.OnPropertyChanged("Title");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="DiscussionTitle", Storage="_discussionSubject", ReadOnly=true, FieldType="Computed")]
	public string DiscussionSubject {
		get {
			return this._discussionSubject;
		}
		set {
			if ((value != this._discussionSubject)) {
				this.OnPropertyChanging("DiscussionSubject", this._discussionSubject);
				this._discussionSubject = value;
				this.OnPropertyChanged("DiscussionSubject");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="_UIVersionString", Storage="_version0", ReadOnly=true, FieldType="Text")]
	public string Version0 {
		get {
			return this._version0;
		}
		set {
			if ((value != this._version0)) {
				this.OnPropertyChanging("Version0", this._version0);
				this._version0 = value;
				this.OnPropertyChanged("Version0");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Body", Storage="_body", FieldType="Note")]
	public string Body {
		get {
			return this._body;
		}
		set {
			if ((value != this._body)) {
				this.OnPropertyChanging("Body", this._body);
				this._body = value;
				this.OnPropertyChanged("Body");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="ReplyNoGif", Storage="_reply", ReadOnly=true, FieldType="Computed")]
	public string Reply {
		get {
			return this._reply;
		}
		set {
			if ((value != this._reply)) {
				this.OnPropertyChanging("Reply", this._reply);
				this._reply = value;
				this.OnPropertyChanged("Reply");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="BodyAndMore", Storage="_post", ReadOnly=true, FieldType="Computed")]
	public string Post {
		get {
			return this._post;
		}
		set {
			if ((value != this._post)) {
				this.OnPropertyChanging("Post", this._post);
				this._post = value;
				this.OnPropertyChanged("Post");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Threading", Storage="_threading", ReadOnly=true, FieldType="Computed")]
	public string Threading {
		get {
			return this._threading;
		}
		set {
			if ((value != this._threading)) {
				this.OnPropertyChanging("Threading", this._threading);
				this._threading = value;
				this.OnPropertyChanged("Threading");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="PersonViewMinimal", Storage="_postedBy", ReadOnly=true, FieldType="Computed")]
	public string PostedBy {
		get {
			return this._postedBy;
		}
		set {
			if ((value != this._postedBy)) {
				this.OnPropertyChanging("PostedBy", this._postedBy);
				this._postedBy = value;
				this.OnPropertyChanged("PostedBy");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="DiscussionLastUpdated", Storage="_lastUpdated", ReadOnly=true, FieldType="DateTime")]
	public System.Nullable<System.DateTime> LastUpdated {
		get {
			return this._lastUpdated;
		}
		set {
			if ((value != this._lastUpdated)) {
				this.OnPropertyChanging("LastUpdated", this._lastUpdated);
				this._lastUpdated = value;
				this.OnPropertyChanged("LastUpdated");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="EmailSender", Storage="_eMailSender", FieldType="Note")]
	public string EMailSender {
		get {
			return this._eMailSender;
		}
		set {
			if ((value != this._eMailSender)) {
				this.OnPropertyChanging("EMailSender", this._eMailSender);
				this._eMailSender = value;
				this.OnPropertyChanged("EMailSender");
			}
		}
	}
	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	[Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
	public override string Name {
		get {
			throw new System.InvalidOperationException("Field FileLeafRef was removed from content type Discussion.");
		}
		set {
			throw new System.InvalidOperationException("Field FileLeafRef was removed from content type Discussion.");
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="MyEditor", Storage="_modifiedById", ReadOnly=true, FieldType="User", IsLookupId=true)]
	public System.Nullable<int> ModifiedById {
		get {
			return this._modifiedById;
		}
		set {
			if ((value != this._modifiedById)) {
				this.OnPropertyChanging("ModifiedById", this._modifiedById);
				this._modifiedById = value;
				this.OnPropertyChanged("ModifiedById");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="MyEditor", Storage="_modifiedByNameWithPicture", ReadOnly=true, FieldType="User", IsLookupValue=true)]
	public string ModifiedByNameWithPicture {
		get {
			return this._modifiedByNameWithPicture;
		}
		set {
			if ((value != this._modifiedByNameWithPicture)) {
				this.OnPropertyChanging("ModifiedByNameWithPicture", this._modifiedByNameWithPicture);
				this._modifiedByNameWithPicture = value;
				this.OnPropertyChanged("ModifiedByNameWithPicture");
			}
		}
	}
}

[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Category", Id="0x01001BE67949DD484746B132BFA579DE4D1A")]
public partial class Category : Item {
	
	private string _categoryName;
	
	private Microsoft.SharePoint.Linq.EntitySet<Machine> _machine;
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public Category() {
		this._machine = new Microsoft.SharePoint.Linq.EntitySet<Machine>();
		this._machine.OnSync += new System.EventHandler<Microsoft.SharePoint.Linq.AssociationChangedEventArgs<Machine>>(this.OnMachineSync);
		this._machine.OnChanged += new System.EventHandler(this.OnMachineChanged);
		this._machine.OnChanging += new System.EventHandler(this.OnMachineChanging);
		this.OnCreated();
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Category_x0020_Name", Storage="_categoryName", FieldType="Text")]
	public string CategoryName {
		get {
			return this._categoryName;
		}
		set {
			if ((value != this._categoryName)) {
				this.OnPropertyChanging("CategoryName", this._categoryName);
				this._categoryName = value;
				this.OnPropertyChanged("CategoryName");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.AssociationAttribute(Name="Machine_x0020_Category", Storage="_machine", ReadOnly=true, MultivalueType=Microsoft.SharePoint.Linq.AssociationType.Backward, List="Machines")]
	public Microsoft.SharePoint.Linq.EntitySet<Machine> Machine {
		get {
			return this._machine;
		}
		set {
			this._machine.Assign(value);
		}
	}
	
	private void OnMachineChanging(object sender, System.EventArgs e) {
		this.OnPropertyChanging("Machine", this._machine.Clone());
	}
	
	private void OnMachineChanged(object sender, System.EventArgs e) {
		this.OnPropertyChanged("Machine");
	}
	
	private void OnMachineSync(object sender, Microsoft.SharePoint.Linq.AssociationChangedEventArgs<Machine> e) {
		if ((Microsoft.SharePoint.Linq.AssociationChangedState.Added == e.State)) {
			e.Item.MachineCategory = this;
		}
		else {
			e.Item.MachineCategory = null;
		}
	}
}

[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Inventory Location", Id="0x01003ADD73260584374BA9AF545AB6ECF52B")]
public partial class InventoryLocation : Item {
	
	private string _binNumber;
	
	private System.Nullable<double> _quantity;
	
	private Microsoft.SharePoint.Linq.EntityRef<Part> _partSKU;
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public InventoryLocation() {
		this._partSKU = new Microsoft.SharePoint.Linq.EntityRef<Part>();
		this._partSKU.OnSync += new System.EventHandler<Microsoft.SharePoint.Linq.AssociationChangedEventArgs<Part>>(this.OnPartSKUSync);
		this._partSKU.OnChanged += new System.EventHandler(this.OnPartSKUChanged);
		this._partSKU.OnChanging += new System.EventHandler(this.OnPartSKUChanging);
		this.OnCreated();
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Bin_x0020_Number", Storage="_binNumber", Required=true, FieldType="Text")]
	public string BinNumber {
		get {
			return this._binNumber;
		}
		set {
			if ((value != this._binNumber)) {
				this.OnPropertyChanging("BinNumber", this._binNumber);
				this._binNumber = value;
				this.OnPropertyChanged("BinNumber");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Quantity", Storage="_quantity", Required=true, FieldType="Number")]
	public System.Nullable<double> Quantity {
		get {
			return this._quantity;
		}
		set {
			if ((value != this._quantity)) {
				this.OnPropertyChanging("Quantity", this._quantity);
				this._quantity = value;
				this.OnPropertyChanged("Quantity");
			}
		}
	}
	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	[Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
	public override string Title {
		get {
			throw new System.InvalidOperationException("Field Title was removed from content type Inventory Location.");
		}
		set {
			throw new System.InvalidOperationException("Field Title was removed from content type Inventory Location.");
		}
	}
	
	[Microsoft.SharePoint.Linq.AssociationAttribute(Name="PartSKU", Storage="_partSKU", MultivalueType=Microsoft.SharePoint.Linq.AssociationType.Single, List="Parts")]
	public Part PartSKU {
		get {
			return this._partSKU.GetEntity();
		}
		set {
			this._partSKU.SetEntity(value);
		}
	}
	
	private void OnPartSKUChanging(object sender, System.EventArgs e) {
		this.OnPropertyChanging("PartSKU", this._partSKU.Clone());
	}
	
	private void OnPartSKUChanged(object sender, System.EventArgs e) {
		this.OnPropertyChanged("PartSKU");
	}
	
	private void OnPartSKUSync(object sender, Microsoft.SharePoint.Linq.AssociationChangedEventArgs<Part> e) {
		if ((Microsoft.SharePoint.Linq.AssociationChangedState.Added == e.State)) {
			e.Item.InventoryLocation.Add(this);
		}
		else {
			e.Item.InventoryLocation.Remove(this);
		}
	}
}

[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Machine Part", Id="0x0100220B06426A421E41A0CA50F1FA1F421F")]
public partial class MachinePart : Item {
	
	private Microsoft.SharePoint.Linq.EntityRef<MachinesMachine> _machine;
	
	private Microsoft.SharePoint.Linq.EntityRef<Part> _part;
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public MachinePart() {
		this._machine = new Microsoft.SharePoint.Linq.EntityRef<MachinesMachine>();
		this._machine.OnSync += new System.EventHandler<Microsoft.SharePoint.Linq.AssociationChangedEventArgs<MachinesMachine>>(this.OnMachineSync);
		this._machine.OnChanged += new System.EventHandler(this.OnMachineChanged);
		this._machine.OnChanging += new System.EventHandler(this.OnMachineChanging);
		this._part = new Microsoft.SharePoint.Linq.EntityRef<Part>();
		this._part.OnSync += new System.EventHandler<Microsoft.SharePoint.Linq.AssociationChangedEventArgs<Part>>(this.OnPartSync);
		this._part.OnChanged += new System.EventHandler(this.OnPartChanged);
		this._part.OnChanging += new System.EventHandler(this.OnPartChanging);
		this.OnCreated();
	}
	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	[Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
	public override string Title {
		get {
			throw new System.InvalidOperationException("Field Title was removed from content type Machine Part.");
		}
		set {
			throw new System.InvalidOperationException("Field Title was removed from content type Machine Part.");
		}
	}
	
	[Microsoft.SharePoint.Linq.AssociationAttribute(Name="Machine", Storage="_machine", MultivalueType=Microsoft.SharePoint.Linq.AssociationType.Single, List="Machines")]
	public MachinesMachine Machine {
		get {
			return this._machine.GetEntity();
		}
		set {
			this._machine.SetEntity(value);
		}
	}
	
	[Microsoft.SharePoint.Linq.AssociationAttribute(Name="Part", Storage="_part", MultivalueType=Microsoft.SharePoint.Linq.AssociationType.Single, List="Parts")]
	public Part Part {
		get {
			return this._part.GetEntity();
		}
		set {
			this._part.SetEntity(value);
		}
	}
	
	private void OnMachineChanging(object sender, System.EventArgs e) {
		this.OnPropertyChanging("Machine", this._machine.Clone());
	}
	
	private void OnMachineChanged(object sender, System.EventArgs e) {
		this.OnPropertyChanged("Machine");
	}
	
	private void OnMachineSync(object sender, Microsoft.SharePoint.Linq.AssociationChangedEventArgs<MachinesMachine> e) {
		if ((Microsoft.SharePoint.Linq.AssociationChangedState.Added == e.State)) {
			e.Item.MachinePart.Add(this);
		}
		else {
			e.Item.MachinePart.Remove(this);
		}
	}
	
	private void OnPartChanging(object sender, System.EventArgs e) {
		this.OnPropertyChanging("Part", this._part.Clone());
	}
	
	private void OnPartChanged(object sender, System.EventArgs e) {
		this.OnPropertyChanged("Part");
	}
	
	private void OnPartSync(object sender, Microsoft.SharePoint.Linq.AssociationChangedEventArgs<Part> e) {
	}
}

[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Machine", Id="0x01002131F2F6C84FE042A765CDC2C96765F4")]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(MachinesMachine))]
public partial class Machine : Item {
	
	private string _modelNumber;
	
	protected Microsoft.SharePoint.Linq.EntityRef<Manufacturer> _manufacturer;
	
	private Microsoft.SharePoint.Linq.EntityRef<Category> _machineCategory;
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public Machine() {
		this._manufacturer = new Microsoft.SharePoint.Linq.EntityRef<Manufacturer>();
		this._manufacturer.OnSync += new System.EventHandler<Microsoft.SharePoint.Linq.AssociationChangedEventArgs<Manufacturer>>(this.OnManufacturerSync);
		this._manufacturer.OnChanged += new System.EventHandler(this.OnManufacturerChanged);
		this._manufacturer.OnChanging += new System.EventHandler(this.OnManufacturerChanging);
		this._machineCategory = new Microsoft.SharePoint.Linq.EntityRef<Category>();
		this._machineCategory.OnSync += new System.EventHandler<Microsoft.SharePoint.Linq.AssociationChangedEventArgs<Category>>(this.OnMachineCategorySync);
		this._machineCategory.OnChanged += new System.EventHandler(this.OnMachineCategoryChanged);
		this._machineCategory.OnChanging += new System.EventHandler(this.OnMachineCategoryChanging);
		this.OnCreated();
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="ModelNumber", Storage="_modelNumber", Required=true, FieldType="Text")]
	public string ModelNumber {
		get {
			return this._modelNumber;
		}
		set {
			if ((value != this._modelNumber)) {
				this.OnPropertyChanging("ModelNumber", this._modelNumber);
				this._modelNumber = value;
				this.OnPropertyChanged("ModelNumber");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.AssociationAttribute(Name="Manufacturer", Storage="_manufacturer", MultivalueType=Microsoft.SharePoint.Linq.AssociationType.Single, List="Manufacturers")]
	public virtual Manufacturer Manufacturer {
		get {
			return this._manufacturer.GetEntity();
		}
		set {
			this._manufacturer.SetEntity(value);
		}
	}
	
	[Microsoft.SharePoint.Linq.AssociationAttribute(Name="Machine_x0020_Category", Storage="_machineCategory", MultivalueType=Microsoft.SharePoint.Linq.AssociationType.Single, List="Categories")]
	public Category MachineCategory {
		get {
			return this._machineCategory.GetEntity();
		}
		set {
			this._machineCategory.SetEntity(value);
		}
	}
	
	private void OnManufacturerChanging(object sender, System.EventArgs e) {
		this.OnPropertyChanging("Manufacturer", this._manufacturer.Clone());
	}
	
	private void OnManufacturerChanged(object sender, System.EventArgs e) {
		this.OnPropertyChanged("Manufacturer");
	}
	
	private void OnManufacturerSync(object sender, Microsoft.SharePoint.Linq.AssociationChangedEventArgs<Manufacturer> e) {
		if ((Microsoft.SharePoint.Linq.AssociationChangedState.Added == e.State)) {
			e.Item.Machine.Add(this);
		}
		else {
			e.Item.Machine.Remove(this);
		}
	}
	
	private void OnMachineCategoryChanging(object sender, System.EventArgs e) {
		this.OnPropertyChanging("MachineCategory", this._machineCategory.Clone());
	}
	
	private void OnMachineCategoryChanged(object sender, System.EventArgs e) {
		this.OnPropertyChanged("MachineCategory");
	}
	
	private void OnMachineCategorySync(object sender, Microsoft.SharePoint.Linq.AssociationChangedEventArgs<Category> e) {
		if ((Microsoft.SharePoint.Linq.AssociationChangedState.Added == e.State)) {
			e.Item.Machine.Add(this);
		}
		else {
			e.Item.Machine.Remove(this);
		}
	}
}

[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Manufacturer", Id="0x0100AE7CD2D2A3D4BC469EB4E95692B750F3")]
public partial class Manufacturer : Item {
	
	private string _manufacturerAddress;
	
	private Microsoft.SharePoint.Linq.EntitySet<Machine> _machine;
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public Manufacturer() {
		this._machine = new Microsoft.SharePoint.Linq.EntitySet<Machine>();
		this._machine.OnSync += new System.EventHandler<Microsoft.SharePoint.Linq.AssociationChangedEventArgs<Machine>>(this.OnMachineSync);
		this._machine.OnChanged += new System.EventHandler(this.OnMachineChanged);
		this._machine.OnChanging += new System.EventHandler(this.OnMachineChanging);
		this.OnCreated();
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="ManufacturerAddress", Storage="_manufacturerAddress", FieldType="Text")]
	public string ManufacturerAddress {
		get {
			return this._manufacturerAddress;
		}
		set {
			if ((value != this._manufacturerAddress)) {
				this.OnPropertyChanging("ManufacturerAddress", this._manufacturerAddress);
				this._manufacturerAddress = value;
				this.OnPropertyChanged("ManufacturerAddress");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.AssociationAttribute(Name="Manufacturer", Storage="_machine", ReadOnly=true, MultivalueType=Microsoft.SharePoint.Linq.AssociationType.Backward, List="Machines")]
	public Microsoft.SharePoint.Linq.EntitySet<Machine> Machine {
		get {
			return this._machine;
		}
		set {
			this._machine.Assign(value);
		}
	}
	
	private void OnMachineChanging(object sender, System.EventArgs e) {
		this.OnPropertyChanging("Machine", this._machine.Clone());
	}
	
	private void OnMachineChanged(object sender, System.EventArgs e) {
		this.OnPropertyChanged("Machine");
	}
	
	private void OnMachineSync(object sender, Microsoft.SharePoint.Linq.AssociationChangedEventArgs<Machine> e) {
		if ((Microsoft.SharePoint.Linq.AssociationChangedState.Added == e.State)) {
			e.Item.Manufacturer = this;
		}
		else {
			e.Item.Manufacturer = null;
		}
	}
}

[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Part Supplier", Id="0x0100679072FB68AF53409FD9F7E845B4D053")]
public partial class PartSupplier : Item {
	
	private Microsoft.SharePoint.Linq.EntityRef<Part> _part;
	
	private Microsoft.SharePoint.Linq.EntityRef<Supplier> _supplier;
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public PartSupplier() {
		this._part = new Microsoft.SharePoint.Linq.EntityRef<Part>();
		this._part.OnSync += new System.EventHandler<Microsoft.SharePoint.Linq.AssociationChangedEventArgs<Part>>(this.OnPartSync);
		this._part.OnChanged += new System.EventHandler(this.OnPartChanged);
		this._part.OnChanging += new System.EventHandler(this.OnPartChanging);
		this._supplier = new Microsoft.SharePoint.Linq.EntityRef<Supplier>();
		this._supplier.OnSync += new System.EventHandler<Microsoft.SharePoint.Linq.AssociationChangedEventArgs<Supplier>>(this.OnSupplierSync);
		this._supplier.OnChanged += new System.EventHandler(this.OnSupplierChanged);
		this._supplier.OnChanging += new System.EventHandler(this.OnSupplierChanging);
		this.OnCreated();
	}
	
	[Microsoft.SharePoint.Linq.AssociationAttribute(Name="Part", Storage="_part", MultivalueType=Microsoft.SharePoint.Linq.AssociationType.Single, List="Parts")]
	public Part Part {
		get {
			return this._part.GetEntity();
		}
		set {
			this._part.SetEntity(value);
		}
	}
	
	[Microsoft.SharePoint.Linq.AssociationAttribute(Name="Supplier", Storage="_supplier", MultivalueType=Microsoft.SharePoint.Linq.AssociationType.Single, List="Suppliers")]
	public Supplier Supplier {
		get {
			return this._supplier.GetEntity();
		}
		set {
			this._supplier.SetEntity(value);
		}
	}
	
	private void OnPartChanging(object sender, System.EventArgs e) {
		this.OnPropertyChanging("Part", this._part.Clone());
	}
	
	private void OnPartChanged(object sender, System.EventArgs e) {
		this.OnPropertyChanged("Part");
	}
	
	private void OnPartSync(object sender, Microsoft.SharePoint.Linq.AssociationChangedEventArgs<Part> e) {
	}
	
	private void OnSupplierChanging(object sender, System.EventArgs e) {
		this.OnPropertyChanging("Supplier", this._supplier.Clone());
	}
	
	private void OnSupplierChanged(object sender, System.EventArgs e) {
		this.OnPropertyChanged("Supplier");
	}
	
	private void OnSupplierSync(object sender, Microsoft.SharePoint.Linq.AssociationChangedEventArgs<Supplier> e) {
		if ((Microsoft.SharePoint.Linq.AssociationChangedState.Added == e.State)) {
			e.Item.PartSupplier.Add(this);
		}
		else {
			e.Item.PartSupplier.Remove(this);
		}
	}
}

[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Part", Id="0x01001966A9D6EDFEB845A8DD2DDA365BF5DC")]
public partial class Part : Item {
	
	private string _sKU;
	
	private string _description;
	
	private Microsoft.SharePoint.Linq.EntitySet<InventoryLocation> _inventoryLocation;
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public Part() {
		this._inventoryLocation = new Microsoft.SharePoint.Linq.EntitySet<InventoryLocation>();
		this._inventoryLocation.OnSync += new System.EventHandler<Microsoft.SharePoint.Linq.AssociationChangedEventArgs<InventoryLocation>>(this.OnInventoryLocationSync);
		this._inventoryLocation.OnChanged += new System.EventHandler(this.OnInventoryLocationChanged);
		this._inventoryLocation.OnChanging += new System.EventHandler(this.OnInventoryLocationChanging);
		this.OnCreated();
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="SKU", Storage="_sKU", Required=true, FieldType="Text")]
	public string SKU {
		get {
			return this._sKU;
		}
		set {
			if ((value != this._sKU)) {
				this.OnPropertyChanging("SKU", this._sKU);
				this._sKU = value;
				this.OnPropertyChanged("SKU");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="RoutingRuleDescription", Storage="_description", Required=true, FieldType="Text")]
	public string Description {
		get {
			return this._description;
		}
		set {
			if ((value != this._description)) {
				this.OnPropertyChanging("Description", this._description);
				this._description = value;
				this.OnPropertyChanged("Description");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.AssociationAttribute(Name="PartSKU", Storage="_inventoryLocation", ReadOnly=true, MultivalueType=Microsoft.SharePoint.Linq.AssociationType.Backward, List="Inventory Locations")]
	public Microsoft.SharePoint.Linq.EntitySet<InventoryLocation> InventoryLocation {
		get {
			return this._inventoryLocation;
		}
		set {
			this._inventoryLocation.Assign(value);
		}
	}
	
	private void OnInventoryLocationChanging(object sender, System.EventArgs e) {
		this.OnPropertyChanging("InventoryLocation", this._inventoryLocation.Clone());
	}
	
	private void OnInventoryLocationChanged(object sender, System.EventArgs e) {
		this.OnPropertyChanged("InventoryLocation");
	}
	
	private void OnInventoryLocationSync(object sender, Microsoft.SharePoint.Linq.AssociationChangedEventArgs<InventoryLocation> e) {
		if ((Microsoft.SharePoint.Linq.AssociationChangedState.Added == e.State)) {
			e.Item.PartSKU = this;
		}
		else {
			e.Item.PartSKU = null;
		}
	}
}

[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Supplier", Id="0x0100C8F084CAA9580A4CB3E1B290909459F6")]
public partial class Supplier : Item {
	
	private string _dUNS;
	
	private System.Nullable<double> _rating;
	
	private Microsoft.SharePoint.Linq.EntitySet<PartSupplier> _partSupplier;
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public Supplier() {
		this._partSupplier = new Microsoft.SharePoint.Linq.EntitySet<PartSupplier>();
		this._partSupplier.OnSync += new System.EventHandler<Microsoft.SharePoint.Linq.AssociationChangedEventArgs<PartSupplier>>(this.OnPartSupplierSync);
		this._partSupplier.OnChanged += new System.EventHandler(this.OnPartSupplierChanged);
		this._partSupplier.OnChanging += new System.EventHandler(this.OnPartSupplierChanging);
		this.OnCreated();
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="DUNS", Storage="_dUNS", FieldType="Text")]
	public string DUNS {
		get {
			return this._dUNS;
		}
		set {
			if ((value != this._dUNS)) {
				this.OnPropertyChanging("DUNS", this._dUNS);
				this._dUNS = value;
				this.OnPropertyChanged("DUNS");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Rating", Storage="_rating", FieldType="Number")]
	public System.Nullable<double> Rating {
		get {
			return this._rating;
		}
		set {
			if ((value != this._rating)) {
				this.OnPropertyChanging("Rating", this._rating);
				this._rating = value;
				this.OnPropertyChanged("Rating");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.AssociationAttribute(Name="Supplier", Storage="_partSupplier", ReadOnly=true, MultivalueType=Microsoft.SharePoint.Linq.AssociationType.Backward, List="Part Suppliers")]
	public Microsoft.SharePoint.Linq.EntitySet<PartSupplier> PartSupplier {
		get {
			return this._partSupplier;
		}
		set {
			this._partSupplier.Assign(value);
		}
	}
	
	private void OnPartSupplierChanging(object sender, System.EventArgs e) {
		this.OnPropertyChanging("PartSupplier", this._partSupplier.Clone());
	}
	
	private void OnPartSupplierChanged(object sender, System.EventArgs e) {
		this.OnPropertyChanged("PartSupplier");
	}
	
	private void OnPartSupplierSync(object sender, Microsoft.SharePoint.Linq.AssociationChangedEventArgs<PartSupplier> e) {
		if ((Microsoft.SharePoint.Linq.AssociationChangedState.Added == e.State)) {
			e.Item.Supplier = this;
		}
		else {
			e.Item.Supplier = null;
		}
	}
}

/// <summary>
/// Create a new meeting, deadline or other event.
/// </summary>
[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Event", Id="0x0102", List="Calendar")]
public partial class CalendarEvent : Event {
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public CalendarEvent() {
		this.OnCreated();
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="EventDate", Storage="_startTime", Required=true, FieldType="DateTime")]
	public override System.Nullable<System.DateTime> StartTime {
		get {
			return this._startTime;
		}
		set {
			if ((value != this._startTime)) {
				this.OnPropertyChanging("StartTime", this._startTime);
				this._startTime = value;
				this.OnPropertyChanged("StartTime");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Description", Storage="_description", FieldType="Note")]
	public override string Description {
		get {
			return this._description;
		}
		set {
			if ((value != this._description)) {
				this.OnPropertyChanging("Description", this._description);
				this._description = value;
				this.OnPropertyChanged("Description");
			}
		}
	}
}

/// <summary>
/// Track a work item that you or your team needs to complete.
/// </summary>
[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Task", Id="0x0108", List="Tasks")]
public partial class TasksTask : Task {
	
	private Microsoft.SharePoint.Linq.EntitySet<Item> _predecessors;
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public TasksTask() {
		this._predecessors = new Microsoft.SharePoint.Linq.EntitySet<Item>();
		this._predecessors.OnSync += new System.EventHandler<Microsoft.SharePoint.Linq.AssociationChangedEventArgs<Item>>(this.OnPredecessorsSync);
		this._predecessors.OnChanged += new System.EventHandler(this.OnPredecessorsChanged);
		this._predecessors.OnChanging += new System.EventHandler(this.OnPredecessorsChanging);
		this.OnCreated();
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="DueDate", Storage="_dueDate", FieldType="DateTime")]
	public override System.Nullable<System.DateTime> DueDate {
		get {
			return this._dueDate;
		}
		set {
			if ((value != this._dueDate)) {
				this.OnPropertyChanging("DueDate", this._dueDate);
				this._dueDate = value;
				this.OnPropertyChanged("DueDate");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Status", Storage="_taskStatus", FieldType="Choice")]
	public override System.Nullable<TaskStatus> TaskStatus {
		get {
			return this._taskStatus;
		}
		set {
			if ((value != this._taskStatus)) {
				this.OnPropertyChanging("TaskStatus", this._taskStatus);
				this._taskStatus = value;
				this.OnPropertyChanged("TaskStatus");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.AssociationAttribute(Name="Predecessors", Storage="_predecessors", MultivalueType=Microsoft.SharePoint.Linq.AssociationType.Multi, List="Tasks")]
	public Microsoft.SharePoint.Linq.EntitySet<Item> Predecessors {
		get {
			return this._predecessors;
		}
		set {
			this._predecessors.Assign(value);
		}
	}
	
	private void OnPredecessorsChanging(object sender, System.EventArgs e) {
		this.OnPropertyChanging("Predecessors", this._predecessors.Clone());
	}
	
	private void OnPredecessorsChanged(object sender, System.EventArgs e) {
		this.OnPropertyChanged("Predecessors");
	}
	
	private void OnPredecessorsSync(object sender, Microsoft.SharePoint.Linq.AssociationChangedEventArgs<Item> e) {
	}
}

/// <summary>
/// Group and describe related tasks that you or your team needs to complete.
/// </summary>
[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Summary Task", Id="0x012004", List="Tasks")]
public partial class TasksSummaryTask : SummaryTask {
	
	private Microsoft.SharePoint.Linq.EntitySet<Item> _predecessors;
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public TasksSummaryTask() {
		this._predecessors = new Microsoft.SharePoint.Linq.EntitySet<Item>();
		this._predecessors.OnSync += new System.EventHandler<Microsoft.SharePoint.Linq.AssociationChangedEventArgs<Item>>(this.OnPredecessorsSync);
		this._predecessors.OnChanged += new System.EventHandler(this.OnPredecessorsChanged);
		this._predecessors.OnChanging += new System.EventHandler(this.OnPredecessorsChanging);
		this.OnCreated();
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="DueDate", Storage="_dueDate", FieldType="DateTime")]
	public override System.Nullable<System.DateTime> DueDate {
		get {
			return this._dueDate;
		}
		set {
			if ((value != this._dueDate)) {
				this.OnPropertyChanging("DueDate", this._dueDate);
				this._dueDate = value;
				this.OnPropertyChanged("DueDate");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Status", Storage="_taskStatus", FieldType="Choice")]
	public override System.Nullable<TaskStatus> TaskStatus {
		get {
			return this._taskStatus;
		}
		set {
			if ((value != this._taskStatus)) {
				this.OnPropertyChanging("TaskStatus", this._taskStatus);
				this._taskStatus = value;
				this.OnPropertyChanged("TaskStatus");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.AssociationAttribute(Name="Predecessors", Storage="_predecessors", MultivalueType=Microsoft.SharePoint.Linq.AssociationType.Multi, List="Tasks")]
	public Microsoft.SharePoint.Linq.EntitySet<Item> Predecessors {
		get {
			return this._predecessors;
		}
		set {
			this._predecessors.Assign(value);
		}
	}
	
	private void OnPredecessorsChanging(object sender, System.EventArgs e) {
		this.OnPropertyChanging("Predecessors", this._predecessors.Clone());
	}
	
	private void OnPredecessorsChanged(object sender, System.EventArgs e) {
		this.OnPropertyChanged("Predecessors");
	}
	
	private void OnPredecessorsSync(object sender, Microsoft.SharePoint.Linq.AssociationChangedEventArgs<Item> e) {
	}
}

[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Machine", Id="0x01002131F2F6C84FE042A765CDC2C96765F4", List="Machines")]
public partial class MachinesMachine : Machine {
	
	private Microsoft.SharePoint.Linq.EntitySet<MachinePart> _machinePart;
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public MachinesMachine() {
		this._machinePart = new Microsoft.SharePoint.Linq.EntitySet<MachinePart>();
		this._machinePart.OnSync += new System.EventHandler<Microsoft.SharePoint.Linq.AssociationChangedEventArgs<MachinePart>>(this.OnMachinePartSync);
		this._machinePart.OnChanged += new System.EventHandler(this.OnMachinePartChanged);
		this._machinePart.OnChanging += new System.EventHandler(this.OnMachinePartChanging);
		this.OnCreated();
	}
	
	[Microsoft.SharePoint.Linq.AssociationAttribute(Name="Machine", Storage="_machinePart", ReadOnly=true, MultivalueType=Microsoft.SharePoint.Linq.AssociationType.Backward, List="Machine Parts")]
	public Microsoft.SharePoint.Linq.EntitySet<MachinePart> MachinePart {
		get {
			return this._machinePart;
		}
		set {
			this._machinePart.Assign(value);
		}
	}
	
	[Microsoft.SharePoint.Linq.AssociationAttribute(Name="Manufacturer0", Storage="_manufacturer", MultivalueType=Microsoft.SharePoint.Linq.AssociationType.Single, List="Manufacturers")]
	public override Manufacturer Manufacturer {
		get {
			return this._manufacturer.GetEntity();
		}
		set {
			this._manufacturer.SetEntity(value);
		}
	}
	
	private void OnMachinePartChanging(object sender, System.EventArgs e) {
		this.OnPropertyChanging("MachinePart", this._machinePart.Clone());
	}
	
	private void OnMachinePartChanged(object sender, System.EventArgs e) {
		this.OnPropertyChanged("MachinePart");
	}
	
	private void OnMachinePartSync(object sender, Microsoft.SharePoint.Linq.AssociationChangedEventArgs<MachinePart> e) {
		if ((Microsoft.SharePoint.Linq.AssociationChangedState.Added == e.State)) {
			e.Item.Machine = this;
		}
		else {
			e.Item.Machine = null;
		}
	}
}

public enum Category0 : int {
	
	None = 0,
	
	Invalid = 1,
	
	[Microsoft.SharePoint.Linq.ChoiceAttribute(Value="(1) Category1")]
	_1Category1 = 2,
	
	[Microsoft.SharePoint.Linq.ChoiceAttribute(Value="(2) Category2")]
	_2Category2 = 4,
	
	[Microsoft.SharePoint.Linq.ChoiceAttribute(Value="(3) Category3")]
	_3Category3 = 8,
}

public enum Priority : int {
	
	None = 0,
	
	Invalid = 1,
	
	[Microsoft.SharePoint.Linq.ChoiceAttribute(Value="(1) High")]
	_1High = 2,
	
	[Microsoft.SharePoint.Linq.ChoiceAttribute(Value="(2) Normal")]
	_2Normal = 4,
	
	[Microsoft.SharePoint.Linq.ChoiceAttribute(Value="(3) Low")]
	_3Low = 8,
}

public enum TaskStatus : int {
	
	None = 0,
	
	Invalid = 1,
	
	[Microsoft.SharePoint.Linq.ChoiceAttribute(Value="Not Started")]
	NotStarted = 2,
	
	[Microsoft.SharePoint.Linq.ChoiceAttribute(Value="In Progress")]
	InProgress = 4,
	
	[Microsoft.SharePoint.Linq.ChoiceAttribute(Value="Completed")]
	Completed = 8,
	
	[Microsoft.SharePoint.Linq.ChoiceAttribute(Value="Deferred")]
	Deferred = 16,
	
	[Microsoft.SharePoint.Linq.ChoiceAttribute(Value="Waiting on someone else")]
	WaitingOnSomeoneElse = 32,
}
