ALTER TABLE [dbo].[MachineParts]
    ADD CONSTRAINT [aaaaaMachineParts_PK] PRIMARY KEY NONCLUSTERED ([MachineId] ASC, [PartSKU] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

