ALTER TABLE [dbo].[Parts]
    ADD CONSTRAINT [aaaaaParts_PK] PRIMARY KEY NONCLUSTERED ([SKU] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

