ALTER TABLE [dbo].[Categories]
    ADD CONSTRAINT [aaaaaFunctionalAreas_PK] PRIMARY KEY NONCLUSTERED ([ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

